import {cancelPointerClick} from './input-guard.mjs';
import {equipmentDuration} from './growth-data.mjs';
import {ICE,iceUnits,guideStep} from './craft-data.mjs';
import {iceMarkup,updateIce} from './cup.mjs';
export class CraftUI{
 constructor(g,ui,audio,getScene){this.g=g;this.ui=ui;this.audio=audio;this.getScene=getScene;this.pointer=null;this.bind();}
 stop(){const held=this.g.craft.held;if(this.pointer!==null)cancelPointerClick(this.pointer);this.g.craft.stop();const box=document.getElementById('ice-add');box.classList.remove('holding');if(this.pointer!==null&&box.hasPointerCapture(this.pointer))box.releasePointerCapture(this.pointer);this.pointer=null;if(held)this.ui.render();}
 ice(){this.ui.render();document.documentElement.style.setProperty('--unit-fall-duration',(equipmentDuration(this.g.data,'ice')*.35)+'s');this.ui.els.cup.classList.toggle('premium-ice',this.g.data.equipmentData.iceMachine===3);const d={...this.g.drink};if(['tea','milk','strawberryJam'].includes(this.ui.activeIngredient))d[this.ui.activeIngredient]=1;updateIce(document.getElementById('ice-cubes'),d,iceUnits(d)-1);this.audio.play('ice');this.ui.animate(this.ui.els.cup,'bump');this.getScene()?.scoop('ice');}
 fly(type){if(type==='seal'){this.getScene()?.scoop('seal');return;}this.getScene()?.scoop(type);if(this.getScene()?.business||this.g.data.settings.lowEffects)return;const colors={tea:'#aa7038',milk:'#fff3d5',pearl:'#49322b',coconut:'#e5eed8',pudding:'#ecc048',redBean:'#94524b',taro:'#b894ce',cream:'#fff9e7',strawberry:'#dd5777',strawberryJam:'#e984a2'};const source=document.querySelector(`[data-ingredient="${type}"]`),root=document.getElementById('ingredient-flight'),cup=document.getElementById('cup');if(!source||root.childElementCount>10)return;const a=source.getBoundingClientRect(),b=cup.getBoundingClientRect(),r=root.getBoundingClientRect();for(let i=0;i<3;i++){const dot=document.createElement('i');dot.className='flying-ingredient';dot.style.cssText=`left:${a.x+a.width/2-r.x}px;top:${a.y+8-r.y}px;--material-color:${colors[type]||'#afad80'};--fly-x:${b.x+b.width/2-a.x-a.width/2+(i-1)*7}px;--fly-y:${b.y+b.height*.13-a.y-8}px;animation-delay:${i*.025}s`;root.append(dot);dot.addEventListener('animationend',()=>dot.remove(),{once:true});}}
 bind(){const box=document.getElementById('ice-add');box.addEventListener('pointerdown',e=>{if(e.button!==0||this.pointer!==null)return;e.preventDefault();e.stopPropagation();this.audio.unlock();if(this.g.phase==='order')this.g.orderSystem.accept();if(this.g.craft.start(e.pointerId)){this.pointer=e.pointerId;box.setPointerCapture(e.pointerId);box.classList.add('holding');}});box.addEventListener('pointermove',e=>{if(e.pointerId!==this.pointer)return;const r=box.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom){this.stop();}});box.addEventListener('pointerup',e=>{if(e.pointerId===this.pointer){e.preventDefault();this.stop();}});box.addEventListener('pointercancel',()=>this.stop());box.addEventListener('lostpointercapture',()=>{if(this.pointer!==null)this.stop();});box.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();if(e.detail===0){this.g.craft.start('keyboard');this.stop();}});box.addEventListener('contextmenu',e=>e.preventDefault());
 document.getElementById('ice-remove').onclick=()=>{this.stop();if(this.g.craft.removeIce()){this.ui.render();this.audio.play('iceRemove');this.getScene()?.scoop('iceRemove');}else if(!iceUnits(this.g.drink)){this.audio.play('click');this.ui.toast('杯里已经没有冰块啦',.8);}};
 document.getElementById('order').addEventListener('click',()=>{if(this.g.phase==='order')this.g.orderSystem.accept();});
 document.getElementById('reference-toggle').onchange=e=>{this.g.data.tutorialState.referenceHintEnabled=e.target.checked;this.g.persist();this.ui.renderDrink(this.g.drink);};
 document.getElementById('effects-toggle').onchange=e=>{this.g.data.settings.lowEffects=e.target.checked;this.g.persist();this.ui.renderDrink(this.g.drink);};
 document.getElementById('save-retry').onclick=()=>{this.g.persist();if(this.g.save.available){document.getElementById('save-retry').hidden=true;this.ui.toast('进度保存好啦');document.getElementById('save-note').textContent='进度会自动保存在当前浏览器';}};
 window.addEventListener('blur',()=>this.stop());document.addEventListener('visibilitychange',()=>this.stop());window.addEventListener('pagehide',()=>this.stop());
 }
}
