import {ShopHomeUI} from './shop-home-ui.mjs';
import {storeLevels,equipmentCatalog,furnitureCatalog,finishes,decorSlots,furnitureEffects,businessGoal,milestones,equipmentDuration} from './growth-data.mjs';
import {decorSlot,placementReason} from './placement.mjs';
import {customers} from './data.mjs';
const $=id=>document.getElementById(id);
export class GrowthUI {
 constructor(g,ui,audio,getScene){this.g=g;this.ui=ui;this.audio=audio;this.getScene=getScene;this.category='decoration';this.draft=null;this.expected=1;this.buyId=null;this.pointer=null;this.homeUI=new ShopHomeUI(this);this.bind();this.render();}
 get scene(){return this.getScene();}
 sound(){this.audio.play('click');}
 render(){const g=this.g,s=g.data,home=g.phase==='idle',decor=g.growth.decorating;const effects=furnitureEffects(s);$('game').dataset.mode=decor?'decor':home?'home':'business';$('store-name').textContent=storeLevels[s.storeLevel].name;document.querySelector('.level-number').textContent=`店铺 LV.${s.storeLevel}`;
  $('home-nav').hidden=!home||decor||!this.ui.ready;$('store-open').disabled=!this.ui.ready;$('home-goals').hidden=!home||decor;$('business-strip').hidden=!g.day||g.phase==='summary'||g.phase==='upgrading';$('decor-panel').hidden=!decor;$('decor-header').hidden=!decor;$('placement-map').hidden=!decor;
  $('comfort-label').textContent=`🪴 舒适度 ${effects.comfort}`;$('decor-comfort').textContent=`🍪 ${s.cookies} · 舒适 ${effects.comfort}`;
  $('business-progress').style.width=(g.day?100*g.day.served/g.day.goal:0)+'%';const target=g.growth.nextTarget();$('next-target').querySelector('b').textContent=target.text;$('next-target').querySelector('small').textContent=`${target.cost?Math.max(0,target.cost-s.cookies)?`还差 ${Math.max(0,target.cost-s.cookies)} 🍪`:'饼干够啦，去看看':target.type==='story'?'查看熟客故事':'挑一件喜欢的装饰'}${target.day&&s.day<target.day?` · DAY ${target.day}`:''}`;
  this.homeUI.render();const goal=s.dailyGoal;$('home-daily').textContent=goal?`${g.growth.goalText()} · ${Math.min(goal.progress,goal.target)}/${goal.target}${goal.claimed?' ✓':''}`:'开门前，看看今天的小目标';
  if($('equipment-page').open)this.equipmentPage(false);if(decor)this.renderDecor();
  if(g.phase==='summary'){
   const a=g.day,rows=[['饮品收入',Math.max(0,(a.salesIncome??a.income)-(a.tips||0)-(a.bonuses||0))],['小费',a.tips||0],['完美连击',a.bonuses||0],['今日目标',a.goalReward||0],['经营里程碑',a.milestoneReward||0],['收藏与成就',a.collectionReward||0],['杯子与材料',-(a.materialCost||0)]];
   $('income-breakdown').innerHTML=rows.map(([name,value])=>`<div><dt>${name}</dt><dd>${value} 🍪</dd></div>`).join('');$('summary-growth').textContent='';$('summary-target').textContent='下一步：'+target.text+(target.cost?` · ${s.cookies>=target.cost?'饼干够啦':`还差 ${target.cost-s.cookies} 🍪`}`:'')+(target.day&&s.day<target.day?` · DAY ${target.day} 可升级`:'');$('continue').textContent='经营小店 · 下一天';
  }
 }
 prepare(){if(!this.g.growth.guard()||this.g.growth.decorating)return;const s=this.g.data,goal=this.g.growth.prepareDay();this.g.persist();$('prep-day').textContent=`DAY ${s.day} · 准备开店`;$('prep-flow').textContent=`预计接待 ${Math.min(14,businessGoal(s)+goal.extra)} 位顾客`;$('prep-note').textContent=s.dayPlan?.eventId==='school'?'放学后，门口可能热闹起来。':s.dayPlan?.eventId==='rain'?'天空有点阴，热茶和雨声很相配。':'茶香刚刚好，慢慢迎接今天。';$('prep-goal').textContent=this.g.growth.goalText();$('prep-reward').textContent=`完成 +${goal.reward} 🍪 · 没完成也没关系`;this.renderGoalChoices();if(!$('preparation').open)$('preparation').showModal();this.sound();}
 renderGoalChoices(){const goal=this.g.data.dailyGoal;$('prep-choices').innerHTML=this.g.growth.goalOptions().map(o=>`<button data-daily-choice="${o.kind}" aria-pressed="${goal?.kind===o.kind&&goal?.target===o.target}"><b>${o.label}</b><small>${this.g.growth.goalText(o)}</small><em>+${o.reward} 🍪</em></button>`).join('');}
 storePage(){this.homeUI.open();}
 equipmentPage(open=true){if(!this.g.growth.guard())return;const s=this.g.data;$('equipment-cards').innerHTML=Object.entries(equipmentCatalog).map(([id,e])=>{const level=s.equipmentData[id],locked=level===2&&s.storeLevel<3,url=this.scene?.shopArt.thumbnail('equipment',id,level);return `<article><img src="${url||''}" alt="${e.labels[level-1]}"><b>${e.name} LV${level}</b><p>${e.feel[level-1]}</p><small>${level<3?'下一阶：'+e.feel[level]:'已经是最高级啦'}</small><button data-upgrade-equipment="${id}" data-level="${level}" ${level===3||locked?'disabled':''}>${level===3?'已满级':locked?'店铺 LV3 解锁':`${e.prices[level]} 🍪 升级`}</button></article>`;}).join('');if(open)$('equipment-page').showModal();}
 openDecor(){if(!this.g.growth.guard())return;if(this.g.phase==='summary'){this.g.nextDay();$('summary').close();}this.g.growth.decorating=true;this.category='decoration';this.draft=null;this.render();this.sound();requestAnimationFrame(()=>this.renderMarkers());}
 closeDecor(){if(this.pointer!==null&&$('placement-map').hasPointerCapture(this.pointer))$('placement-map').releasePointerCapture(this.pointer);this.pointer=null;this.cancelDraft();this.g.growth.decorating=false;this.render();this.ui.render();this.scene?.setState(this.g.phase);}
 renderDecor(){const s=this.g.data,root=$('decor-catalog');for(const b of document.querySelectorAll('[data-decor-category]'))b.classList.toggle('selected',b.dataset.decorCategory===this.category);$('placement-controls').hidden=!this.draft;root.hidden=!!this.draft;$('decor-categories').hidden=!!this.draft;
  if(this.draft){const d=this.draft;$('placing-name').textContent=furnitureCatalog[d.id].name;$('placement-store').disabled=!this.g.data.placedFurniture.some(p=>p.uid===d.uid);$('placement-confirm').disabled=!this.g.growth.canPlace(d.id,d.slot,d.uid,d.direction);$('placement-confirm').textContent=this.g.growth.canPlace(d.id,d.slot,d.uid,d.direction)?'放在'+decorSlot(d.slot,s.storeLevel).label:'换个位置';$('placement-hint').textContent=d.slot?(this.g.growth.canPlace(d.id,d.slot,d.uid,d.direction)?'位置合适，点确认留下它':placementReason(s,d.id,d.slot,d.uid,d.direction)||'这件家具还没有放进仓库'):'点一个位置，或拖到圆点附近';this.renderMarkers();return;}
  const cards=[];if(['wall','floor','sign'].includes(this.category)){for(const[id,f]of Object.entries(finishes[this.category])){const owned=s.ownedFinishes[this.category].includes(id),selected=s[this.category==='wall'?'wallpaper':this.category]===id;cards.push(`<button class="decor-item finish ${selected?'selected':''}" data-finish-kind="${this.category}" data-finish="${id}"><i style="background:${f.color}"></i><b>${f.name}</b><small>${selected?'正在使用':owned?'已拥有 · 换上':`${f.price} 🍪`}</small></button>`);}}
  for(const[id,f]of Object.entries(furnitureCatalog).filter(([,f])=>f.category===this.category)){const owned=s.ownedFurniture[id]||0,spare=this.g.growth.spare(id),locked=s.storeLevel<f.level||f.reward&&!owned;const url=this.scene?.shopArt.thumbnail('furniture',id);cards.push(`<button class="decor-item" data-furniture="${id}" ${locked?'disabled':''}><img src="${url||''}" alt=""><b>${f.name}</b><small>${locked?f.reward?(id==='goldTrophy'?'100 杯纪念':f.description.includes('三张')?'熟客配方纪念':'熟客故事纪念'):`店铺 LV${f.level}`:spare?`仓库 ${spare} · 摆放`:owned?`已摆 ${owned} · ${f.price} 🍪 再买`:`${f.price} 🍪`}</small></button>`);}
  root.innerHTML=cards.join('');this.renderMarkers();
 }
 selectFurniture(id){const f=furnitureCatalog[id];if(this.g.growth.spare(id)>0){const recovered=this.g.data.recoveredFurniture?.find(p=>p.id===id&&/^f[0-9]+$/.test(p.uid));this.startDraft(id,recovered?{...recovered,slot:null}:null);return;}this.buyId=id;$('buy-name').textContent=f.name;$('buy-description').textContent=f.description;$('buy-price').textContent=`${f.price} 🍪`;$('buy-preview').src=this.scene.shopArt.thumbnail('furniture',id);$('furniture-buy').showModal();this.sound();}
 startDraft(id,placed=null){this.cancelDraft();const slot=placed?.slot??decorSlots.find(x=>this.g.growth.canPlace(id,x.id))?.id??null;this.draft={id,uid:placed?.uid||null,slot,direction:placed?.direction||1};if(placed){const model=this.scene.shopArt.objects.get(placed.uid);if(model)model.visible=false;}this.previewDraft();this.renderDecor();}
 cancelDraft(){if(this.draft?.uid){const m=this.scene?.shopArt.objects.get(this.draft.uid);if(m)m.visible=true;}this.draft=null;this.scene?.shopArt.ghost(null);}
 previewDraft(){if(!this.draft)return;const d=this.draft;this.scene?.shopArt.ghost(d.id,d.slot,this.g.growth.canPlace(d.id,d.slot,d.uid,d.direction),d.direction);}
 selectSlot(slot){if(!this.draft||this.draft.slot===slot)return;this.draft.slot=slot;this.previewDraft();this.renderDecor();}
 renderMarkers(){if(!this.g.growth.decorating||!this.scene)return;const d=this.draft,s=this.g.data,map=$('placement-map'),focused=document.activeElement?.dataset.slot;if(d){const placedMarkers=[],bounds=map.getBoundingClientRect();map.innerHTML=decorSlots.filter(slot=>slot.level<=s.storeLevel&&slot.zone===furnitureCatalog[d.id].zone).map(slot=>{const p=this.scene.shopArt.project(slot),valid=this.g.growth.canPlace(d.id,slot.id,d.uid,d.direction);for(let tries=0;tries<8&&placedMarkers.some(q=>Math.abs(q.x-p.x)*bounds.width<50&&Math.abs(q.y-p.y)*bounds.height<64);tries++)p.y-=64/bounds.height;p.x=Math.max(24/bounds.width,Math.min(1-24/bounds.width,p.x));p.y=Math.max(24/bounds.height,Math.min(1-44/bounds.height,p.y));placedMarkers.push({...p});return `<button data-slot="${slot.id}" style="left:${p.x*100}%;top:${p.y*100}%" class="place-dot ${valid?'valid':'invalid'} ${d.slot===slot.id?'selected':''}" aria-pressed="${d.slot===slot.id}" aria-label="${decorSlot(slot.id,s.storeLevel).label}${valid?'可放置':placementReason(s,d.id,slot.id,d.uid,d.direction)}">${valid?'+':'×'}<small>${decorSlot(slot.id,s.storeLevel).label}</small></button>`;}).join('');}else{map.innerHTML='<span class="decor-tip">点击已摆家具可以移动 · 点下方挑新家具</span>';}if(focused&&d)map.querySelector(`[data-slot="${focused}"]`)?.focus({preventScroll:true});}
 onGrowth(e){this.ui.setMoney(this.g.data.cookies);if(e.kind!=='purchase')this.scene?.applyGrowth(this.g.data);if(e.kind==='placement'){this.scene?.moodFor('happy',1);this.ui.particles(5,.4,.4);}this.render();}
 bind(){
 $('decor-open').onclick=()=>this.openDecor();$('decor-back').onclick=()=>this.closeDecor();$('equipment-open').onclick=()=>this.equipmentPage();$('store-open').onclick=()=>this.storePage();$('more-open').onclick=()=>{$('more-menu').showModal();this.sound();};$('more-recipes').onclick=()=>{$('more-menu').close();this.ui.recipeBook();};$('more-settings').onclick=()=>{$('more-menu').close();$('settings-open').click();};$('collection-open').onclick=()=>{$('more-menu').close();$('customer-collection').innerHTML=Object.entries(customers).map(([k,c])=>`<article><span>${c.icon}</span><b>${this.g.data.seenCustomers.includes(k)?c.name:'还未相遇'}</b><small>${this.g.data.seenCustomers.includes(k)?'来过小店啦':c.store?'旗舰店来客':'下次会见到谁呢'}</small></article>`).join('');$('collection-page').showModal();};
 $('next-target').onclick=()=>{const t=this.g.growth.nextTarget();t.type==='store'?this.storePage():t.type==='equipment'?this.equipmentPage():this.openDecor();};
 $('open-business').onclick=()=>{$('preparation').close();this.g.start();this.sound();};
 $('store-confirm-open').onclick=()=>{this.expected=this.g.data.storeLevel;const next=storeLevels[this.expected+1];if(!next)return;$('shop-confirm-title').textContent=`升级${next.name}？`;$('shop-confirm-cost').textContent=`需要 ${next.cost} 🍪 · 立即完成`;$('shop-confirm').showModal();};
 $('shop-upgrade-do').onclick=()=>{if(this.g.growth.upgradeStore(this.expected)){$('shop-confirm').close();$('store-page').close();this.sound();}};
 $('buy-do').onclick=()=>{if(this.g.growth.buyFurniture(this.buyId)){$('furniture-buy').close();this.startDraft(this.buyId);this.sound();}};
 $('placement-cancel').onclick=()=>{this.cancelDraft();this.renderDecor();};$('placement-rotate').onclick=()=>{if(this.draft){this.draft.direction*=-1;this.previewDraft();this.renderDecor();this.sound();}};
 $('placement-move').onclick=()=>{this.ui.toast('拖到圆点附近，或直接点圆点');this.renderMarkers();};
 $('placement-confirm').onclick=()=>{const d=this.draft;if(d&&this.g.growth.place(d.id,d.slot,d.direction,d.uid)){this.cancelDraft();this.renderDecor();this.sound();}};
 $('placement-store').onclick=()=>{if(this.draft?.uid&&this.g.growth.store(this.draft.uid)){this.cancelDraft();this.renderDecor();this.sound();}};
 document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b||b.disabled)return;if(b.dataset.dailyChoice){if(this.g.growth.chooseGoal(b.dataset.dailyChoice)){this.prepare();this.render();}}if(b.dataset.upgradeEquipment){this.g.growth.upgradeEquipment(b.dataset.upgradeEquipment,Number(b.dataset.level));this.sound();}if(b.dataset.decorCategory){this.category=b.dataset.decorCategory;this.renderDecor();this.sound();}if(b.dataset.furniture)this.selectFurniture(b.dataset.furniture);if(b.dataset.slot)this.selectSlot(b.dataset.slot);if(b.dataset.finish){this.g.growth.buyFinish(b.dataset.finishKind,b.dataset.finish);this.sound();}});
 const map=$('placement-map');map.addEventListener('pointerdown',e=>{const slotButton=e.target.closest('[data-slot]');if(slotButton){e.preventDefault();e.stopPropagation();this.selectSlot(slotButton.dataset.slot);return;}if(e.target.closest('button'))return;if(!this.draft){const uid=this.scene?.rayFurniture(e.clientX,e.clientY);const p=this.g.data.placedFurniture.find(p=>p.uid===uid);if(p)this.startDraft(p.id,p);return;}e.preventDefault();e.stopPropagation();map.setPointerCapture(e.pointerId);this.pointer=e.pointerId;});
 map.addEventListener('pointermove',e=>{if(this.pointer!==e.pointerId||!this.draft)return;e.preventDefault();const box=map.getBoundingClientRect(),x=(e.clientX-box.left)/box.width,y=(e.clientY-box.top)/box.height;let nearest=null,dist=.17;for(const slot of decorSlots.filter(x=>x.level<=this.g.data.storeLevel&&x.zone===furnitureCatalog[this.draft.id].zone)){const p=this.scene.shopArt.project(slot),d=Math.hypot(x-p.x,y-p.y);if(d<dist){dist=d;nearest=slot.id;}}this.selectSlot(nearest);});
 const end=e=>{if(this.pointer===e.pointerId){this.pointer=null;if(map.hasPointerCapture(e.pointerId))map.releasePointerCapture(e.pointerId);}};map.addEventListener('pointerup',end);map.addEventListener('pointercancel',end);
 $('shop-canvas').addEventListener('click',e=>{if(this.g.phase!=='idle'||this.g.growth.decorating)return;const uid=this.scene?.rayFurniture(e.clientX,e.clientY);if(uid)this.g.growth.interact(uid);});
 this.resize=new ResizeObserver(()=>this.renderMarkers());this.resize.observe($('scene-wrap'));
 }
}
