import {decorSlot,placementReason,reconcilePlacements} from './placement.mjs';
import {storeLevels,equipmentCatalog,furnitureCatalog,finishes,decorSlots,milestones,freshGrowth,furnitureEffects,businessGoal} from './growth-data.mjs';
export class GrowthSystem {
 constructor(game){this.g=game;game.growth=this;this.locks=new Map();this.decorating=false;}
 get editable(){return this.g.phase==='idle'&&!this.g.busy;}
 guard(){if(!this.editable){this.g.emit('notice',{message:'先忙完今天的营业吧～'});return false;}return true;}
 once(key){if((this.locks.get(key)||-1)>this.g.clock)return false;this.locks.set(key,this.g.clock+.6);return true;}
 spend(amount){if(this.g.data.cookies<amount){this.g.emit('shortMoney',{missing:amount-this.g.data.cookies});return false;}this.g.data.cookies-=amount;return true;}
 changed(kind,detail={}){this.g.data.comfort=furnitureEffects(this.g.data).comfort;this.g.persist();this.g.emit('growth',{kind,...detail});}
 upgradeStore(expected){const g=this.g,s=g.data,next=storeLevels[s.storeLevel+1];if(!this.guard()||!next||expected!==s.storeLevel||!this.once('store'))return false;if(s.day<next.day){g.emit('notice',{message:`DAY ${next.day} 再把小店升级吧～`});return false;}if(!this.spend(next.cost))return false;const previous=s.storeLevel;s.storeLevel++;reconcilePlacements(s);s.storeReactions=4;g.busy=true;g.setPhase('upgrading');g.persist();g.emit('storeUpgrade',{previous,level:s.storeLevel});g.later(1.6,()=>{g.busy=false;g.setPhase('idle');this.changed('store');g.emit('storeOpened',{name:next.name});});return true;}
 upgradeEquipment(id,expected){const s=this.g.data,e=equipmentCatalog[id],level=s.equipmentData[id];if(!this.guard()||!e||expected!==level||level>=3||!this.once('equipment:'+id))return false;if(level===2&&s.storeLevel<3){this.g.emit('notice',{message:'升到室内茶铺后，可升级 LV3 设备'});return false;}if(!this.spend(e.prices[level]))return false;s.equipmentData[id]++;this.changed('equipment',{id});return true;}
 buyFurniture(id){const f=furnitureCatalog[id],s=this.g.data;if(!this.guard()||!f||f.reward||s.storeLevel<f.level||!this.once('buy:'+id))return false;if(!this.spend(f.price))return false;s.ownedFurniture[id]=(s.ownedFurniture[id]||0)+1;this.changed('purchase',{id});return true;}
 spare(id,except=null){return (this.g.data.ownedFurniture[id]||0)-this.g.data.placedFurniture.filter(p=>p.id===id&&p.uid!==except).length;}
 canPlace(id,slotId,uid=null,direction=1){return this.spare(id,uid)>0&&!placementReason(this.g.data,id,slotId,uid,direction);}
 place(id,slot,direction=1,uid=null){if(!this.guard()||!this.canPlace(id,slot,uid,direction)||!this.once('place'))return false;const s=this.g.data,p=decorSlot(slot,s.storeLevel);const item={uid:uid||`f${s.nextFurnitureId++}`,id,slot,x:p.pos[0],y:p.pos[2],direction:direction===-1?-1:1,on:true};const existing=s.placedFurniture.findIndex(x=>x.uid===uid);if(existing>=0){item.on=s.placedFurniture[existing].on;s.placedFurniture[existing]=item;}else s.placedFurniture.push(item);if(s.recoveredFurniture)s.recoveredFurniture=s.recoveredFurniture.filter(p=>p.uid!==item.uid);this.changed('placement',{item});return item;}
 store(uid){if(!this.guard()||!this.once('store:'+uid))return false;const s=this.g.data,index=s.placedFurniture.findIndex(x=>x.uid===uid);if(index<0)return false;s.placedFurniture.splice(index,1);this.changed('storage');return true;}
 buyFinish(kind,id){const s=this.g.data,f=finishes[kind]?.[id];if(!this.guard()||!f||!this.once('finish:'+kind))return false;if(kind==='wall'&&s.storeLevel<3){this.g.emit('notice',{message:'进入室内茶铺后就能换墙面啦'});return false;}if(!s.ownedFinishes[kind].includes(id)){if(!this.spend(f.price))return false;s.ownedFinishes[kind].push(id);}s[kind==='wall'?'wallpaper':kind]=id;this.changed('finish',{id});return true;}
 interact(uid){const p=this.g.data.placedFurniture.find(x=>x.uid===uid);if(!p||!this.editable||this.decorating||!this.once('interact'))return false;const f=furnitureCatalog[p.id];if(!['chair','smallPlant','largePlant','doll','frogSign','lamp','stringLights','grannyCoaster','warmLamp','townPostcard','handDrawnMenu'].includes(p.id))return false;if(f.effect==='lamp'){p.on=!p.on;this.g.persist();}this.g.emit('furnitureInteraction',{item:p});return true;}
 goalOptions(){const total=businessGoal(this.g.data),early=this.g.data.day<=3;return [
  {kind:'serve',label:'轻松迎客',target:Math.min(5,total),reward:early?80:60},
  {kind:'quality',label:'认真调茶',target:Math.max(2,Math.ceil(total*.6)),reward:early?110:90},
  {kind:'perfect',label:'冲一冲五星',target:Math.max(2,Math.ceil(total*.5)),reward:early?150:120}
 ];}
 prepareDay(){const g=this.g,s=g.data;g.unlock();g.town?.prepareDay();if(s.dailyGoal?.day===s.day)return s.dailyGoal;const chosen=this.goalOptions()[1];return s.dailyGoal={day:s.day,...chosen,progress:0,claimed:false,rush:false,orderIds:[],extra:g.random()<furnitureEffects(s).traffic?1:0};}
 chooseGoal(kind){const g=this.g,s=g.data;if(g.save.readBlocked||g.phase!=='idle'||g.busy||g.day||g.growth.decorating)return false;const chosen=this.goalOptions().find(o=>o.kind===kind);if(!chosen)return false;const old=this.prepareDay();if(old.claimed||old.progress>0)return false;s.dailyGoal={...old,...chosen,progress:0,orderIds:[]};g.persist();g.emit('goalChanged');return true;}
 goalText(goal=this.g.data.dailyGoal){if(!goal)return '';return {serve:`亲手交付 ${goal.target} 杯奶茶`,quality:`做出 ${goal.target} 杯四星以上奶茶`,perfect:`做出 ${goal.target} 杯五星奶茶`,combo:`达到 ${goal.target} 连完美`,children:`接待 ${goal.target} 名小朋友`,income:`今日营业收入达到 ${goal.target} 🍪`}[goal.kind];}
 onOrder(c,rating){const g=this.g,s=g.data,a=g.day,goal=s.dailyGoal;let reward=0;const messages=[];
  if(goal?.day===s.day&&!goal.claimed&&!(goal.orderIds||[]).includes(c.id)){goal.orderIds??=[];if(c.id)goal.orderIds.push(c.id);if(goal.kind==='serve')goal.progress++;if(goal.kind==='quality'&&rating>=4)goal.progress++;if(goal.kind==='perfect'&&rating===5)goal.progress++;if(goal.kind==='children'&&c.type==='child')goal.progress++;if(goal.kind==='combo')goal.progress=Math.max(goal.progress,a.combo);if(goal.kind==='income')goal.progress=a.salesIncome??a.income;if(goal.progress>=goal.target){goal.claimed=true;reward+=goal.reward;messages.push(`今日小目标完成 +${goal.reward} 🍪`);a.goalReward=(a.goalReward||0)+goal.reward;}}
  for(const m of milestones){if(!s.milestones.includes(m.id)&&!s.rewardLedger?.['milestone:'+m.id]&&s.stats[m.kind]>=m.target){s.milestones.push(m.id);s.rewardLedger['milestone:'+m.id]=true;reward+=m.reward;if(m.furniture)s.ownedFurniture[m.furniture]=(s.ownedFurniture[m.furniture]||0)+1;messages.push(`${m.name}${m.furniture?' · 获得金色小奖杯':` +${m.reward} 🍪`}`);}}
  g.costs.credit(reward);a.income+=reward;a.milestoneReward=(a.milestoneReward||0)+reward-(goal?.claimed&&(a.goalReward||0)&&messages[0]?.includes('小目标')?goal.reward:0);
  if(messages.length)g.emit('growthReward',{messages,reward});
 }
 nextTarget(){const s=this.g.data;const story=this.g.town?.nextTarget();if(story)return story;if(!Object.values(s.ownedFurniture).some(Boolean))return {text:'第一盆小绿植',cost:100,type:'decor'};if(s.equipmentData.sealer===1&&s.storeLevel>=2)return {text:'让封口机更顺手',cost:400,type:'equipment'};const next=storeLevels[s.storeLevel+1];if(next)return {text:`升级${next.name}`,cost:next.cost,day:next.day,type:'store'};const k=Object.keys(equipmentCatalog).find(k=>s.equipmentData[k]<3);return k?{text:`升级${equipmentCatalog[k].name}`,cost:equipmentCatalog[k].prices[s.equipmentData[k]],type:'equipment'}:{text:'把小店布置成喜欢的样子',cost:0,type:'decor'};}
}
export function normalizeGrowth(raw,s){const defaults=freshGrowth();for(const[k,v]of Object.entries(defaults))s[k]=structuredClone(v);s.storeLevel=Math.max(1,Math.min(5,Math.floor(Number(raw.storeLevel)||1)));
 for(const k of Object.keys(equipmentCatalog))s.equipmentData[k]=Math.max(1,Math.min(3,Math.floor(Number(raw.equipmentData?.[k])||1)));
 for(const k of Object.keys(furnitureCatalog))if(Number.isFinite(raw.ownedFurniture?.[k]))s.ownedFurniture[k]=Math.max(0,Math.min(1000,Math.floor(raw.ownedFurniture[k])));
 s.nextFurnitureId=Math.max(1,Math.floor(Number(raw.nextFurnitureId)||1));const used=new Set(),uids=new Set();
 for(const p of (Array.isArray(raw.placedFurniture)?raw.placedFurniture:[]).slice(0,30)){const f=furnitureCatalog[p.id],slot=decorSlots.find(x=>x.id===p.slot);if(!f||!slot||used.has(p.slot)||slot.zone!==f.zone||slot.level>s.storeLevel||f.level>s.storeLevel||s.placedFurniture.filter(x=>x.id===p.id).length>=(s.ownedFurniture[p.id]||0))continue;used.add(p.slot);const uid=typeof p.uid==='string'&&/^f[0-9]+$/.test(p.uid)&&!uids.has(p.uid)?p.uid:`f${s.nextFurnitureId++}`;uids.add(uid);s.nextFurnitureId=Math.max(s.nextFurnitureId,Number(uid.slice(1))+1);s.placedFurniture.push({uid,id:p.id,slot:p.slot,x:slot.pos[0],y:slot.pos[2],direction:p.direction===-1?-1:1,on:p.on!==false});}
 for(const kind of Object.keys(finishes)){s.ownedFinishes[kind]=[...new Set([...s.ownedFinishes[kind],...(Array.isArray(raw.ownedFinishes?.[kind])?raw.ownedFinishes[kind]:[]).filter(k=>finishes[kind][k])])];const key=kind==='wall'?'wallpaper':kind;if(s.ownedFinishes[kind].includes(raw[key]))s[key]=raw[key];}
 s.comfort=furnitureEffects(s).comfort;s.milestones=Array.isArray(raw.milestones)?raw.milestones.filter(k=>milestones.some(m=>m.id===k)):[];s.storeReactions=Math.min(4,Math.max(0,Number(raw.storeReactions)||0));s.seenCustomers=Array.isArray(raw.seenCustomers)?raw.seenCustomers.filter(x=>typeof x==='string'):[];
 const d=raw.dailyGoal;if(d&&d.day===s.day&&['serve','quality','perfect','combo','children','income'].includes(d.kind))s.dailyGoal={day:s.day,kind:d.kind,target:Math.max(1,Math.min(300,Number(d.target)||5)),progress:Math.max(0,Number(d.progress)||0),reward:Math.max(50,Math.min(150,Number(d.reward)||100)),claimed:d.claimed===true,orderIds:[...new Set((Array.isArray(d.orderIds)?d.orderIds:[]).filter(id=>typeof id==='string'&&/^\d+-\d+$/.test(id)))].slice(-14),rush:d.rush===true,extra:d.extra===1?1:0};
 reconcilePlacements(s);s.comfort=furnitureEffects(s).comfort;
}
