import {cancelPointerClick} from './input-guard.mjs';
import {GameState,CustomerSystem,OrderSystem,DrinkSystem} from './game.mjs';
import {freshSave,ingredients} from './data.mjs';
import {guideStep,guideText,ICE} from './craft-data.mjs';
import {iceMarkup,toppingMarkup,creamMarkup,liquidColor} from './cup.mjs';
const $=id=>document.getElementById(id);
export class PracticeSession{
 constructor(audio){this.audio=audio;this.pointer=null;this.lastX=null;this.game=null;this.dialog=$('practice-page');this.bind();}
 open(){const save={load:()=>freshSave(),save:()=>true};const g=this.game=new GameState(save,()=>.2);new CustomerSystem(g);new OrderSystem(g);new DrinkSystem(g);g.on(e=>{if(e.type==='iceAdded')this.audio.play('ice');if(e.type==='ingredientStart')this.audio.play(e.ingredient);if(e.type==='perfect')this.audio.play('perfect');this.render();});g.start();for(let i=0;i<40;i++)g.tick(.05);this.done=false;this.dialog.showModal();this.render();}
 tick(dt){if(this.game&&this.dialog.open&&!document.hidden){this.game.tick(dt);if(this.game.phase==='shaking')this.render();}}
 stop(){this.game?.craft.stop();if(this.pointer!==null){cancelPointerClick(this.pointer);const ice=$('practice-ice-add');if(ice.hasPointerCapture(this.pointer))ice.releasePointerCapture(this.pointer);}if(this.shakePointer!=null){cancelPointerClick(this.shakePointer);const shake=$('practice-shake');if(shake.hasPointerCapture(this.shakePointer))shake.releasePointerCapture(this.shakePointer);}this.pointer=null;this.shakePointer=null;this.lastX=null;}
 render(){const g=this.game;if(!g)return;const d=g.drink,step=guideStep(g.current);$('practice-guide').textContent=this.done?'练会啦！回到小店，做一杯真正的奶茶吧。':g.phase==='ready'?'摇得很好，递出这杯就完成练习啦':guideText[step]||'亲手左右摇动';if(d){$('practice-cup').innerHTML=`<svg viewBox="0 0 150 190"><defs><clipPath id="practice-clip"><path d="M32 42H118L106 168Q75 181 44 168Z"/></clipPath></defs><g clip-path="url(#practice-clip)"><path d="M30 ${d.milk?66:d.tea?103:176}H120V180H30Z" fill="${liquidColor(d)}"/>${toppingMarkup(d)}${iceMarkup(d)}${creamMarkup(d)}${step==='ice'?iceMarkup({...d,iceUnits:4},-1,true):''}</g><path d="M32 42H118L106 168Q75 181 44 168Z" fill="none" stroke="#548476" stroke-width="3"/>${d.sealed?'<path d="M27 35H123V45H27Z" fill="#75b59b"/>':''}</svg>`;}
 const controls=['tea','milk','pearl','seal'].map(k=>`<button data-practice-ingredient="${k}" ${g.phase==='making'&&g.craft.allowed(k)&&!g.busy?'':'disabled'}>${ingredients[k].icon} ${ingredients[k].name}</button>`).join('')+`<button id="practice-sugar" ${step==='sugar'?'':'disabled'}>七分糖</button>`;$('practice-controls').innerHTML=controls;$('practice-ice-add').disabled=g.phase!=='making'||step!=='ice';$('practice-ice-remove').disabled=g.phase!=='making'||step!=='ice'||!d?.iceUnits;$('practice-shake').hidden=g.phase!=='shaking';$('practice-shake').textContent=`左右摇起来 ↔ ${Math.round(d?.shakeScore||0)}%`;
 $('practice-action').textContent=this.done?'返回小店':g.phase==='order'?'看好订单，开始练习':g.phase==='ready'?'递出这杯 · 完成练习':'跟着提示亲手操作';$('practice-action').disabled=!this.done&&!['order','ready'].includes(g.phase);}
 bind(){$('practice-open').onclick=()=>this.open();this.dialog.addEventListener('close',()=>{this.stop();this.game=null;});$('practice-action').onclick=()=>{if(this.done){this.dialog.close();return;}if(this.game.phase==='order')this.game.orderSystem.accept();else if(this.game.phase==='ready'){this.done=true;this.render();this.audio.play('happy');}};
 $('practice-controls').addEventListener('click',e=>{const b=e.target.closest('button');if(!b||b.disabled)return;if(b.dataset.practiceIngredient)this.game.drinkSystem.add(b.dataset.practiceIngredient);if(b.id==='practice-sugar')this.game.drinkSystem.choose('sugar',70);});
 const ice=$('practice-ice-add');ice.onpointerdown=e=>{if(this.pointer!==null)return;e.preventDefault();if(this.game.craft.start(e.pointerId)){this.pointer=e.pointerId;ice.setPointerCapture(e.pointerId);}};ice.onpointermove=e=>{if(this.pointer!==e.pointerId)return;const r=ice.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)this.stop();};ice.onpointerup=e=>{if(e.pointerId===this.pointer){this.stop();this.render();}};ice.onpointercancel=()=>this.stop();ice.onlostpointercapture=()=>this.stop();ice.onclick=e=>e.preventDefault();$('practice-ice-remove').onclick=()=>{this.game.craft.removeIce();this.render();};
 const shake=$('practice-shake');shake.onpointerdown=e=>{if(this.shakePointer!=null)return;e.preventDefault();this.shakePointer=e.pointerId;this.lastX=e.clientX;shake.setPointerCapture(e.pointerId);};shake.onpointermove=e=>{if(this.lastX===null)return;this.game.drinkSystem.shake(e.clientX-this.lastX,0,shake.clientWidth);this.lastX=e.clientX;};shake.onpointerup=shake.onpointercancel=()=>this.stop();document.addEventListener('visibilitychange',()=>this.stop());}
}
