import {storyLines,variants,freshProgress,achievementCatalog,events,townMessages} from './town-data.mjs';
import {customers,drinkRecipes} from './data.mjs';
import {furnitureEffects,storeLevels,businessGoal,milestones} from './growth-data.mjs';
import {iceAssessment} from './craft-data.mjs';
export class TownSystem{
 constructor(g){this.g=g;}
 progress(id){return this.g.data.customerProgress[id]??=freshProgress();}
 eligible(){const s=this.g.data;return Object.keys(storyLines).filter(id=>{const p=this.progress(id);return s.unlocked.includes(storyLines[id].recipe)&&p.storyNode<3&&p.lastStoryDay<s.day;}).sort((a,b)=>(this.progress(a).lastStoryDay-this.progress(b).lastStoryDay)||(this.progress(a).lastVisitDay-this.progress(b).lastVisitDay));}
 prepareDay(){const g=this.g,s=g.data;if(s.dayPlan?.day===s.day)return s.dayPlan;const eligible=this.eligible();let storyCustomerId=null;if(eligible.length&&(s.storyMissDays>=2||g.random()<.55))storyCustomerId=eligible[0];if(g.dev.story&&eligible.includes(g.dev.story))storyCustomerId=g.dev.story;let eventId=null;const pool=['school','rain','postcard'];if(Object.keys(storyLines).some(id=>this.progress(id).met))pool.push('friend');if(s.day>3&&g.random()<.35)eventId=pool[Math.floor(g.random()*pool.length)];if(s.day>3&&g.dev.event&&pool.includes(g.dev.event))eventId=g.dev.event;
  s.dayPlan={day:s.day,storyCustomerId,storySerial:Math.min(3,businessGoal(s)),storyNode:storyCustomerId?this.progress(storyCustomerId).storyNode+1:0,eligible:eligible.length>0,storyAdvanced:false,completedOrderIds:[],eventId,eventTriggered:false,eventRemaining:0,eventApplied:0,discoveries:[],closed:false,postcardIndex:Math.floor(g.random()*townMessages.length)};return s.dayPlan;}
 assign(c,serial){const g=this.g,s=g.data,p=s.dayPlan;if(p?.storyCustomerId&&serial===p.storySerial&&!c.tutorial){const id=p.storyCustomerId,story=storyLines[id],node=story.nodes[p.storyNode-1];if(node&&s.unlocked.includes(story.recipe)){c.type=id;c.recipe=story.recipe;c.sugar=node.sugar;c.ice=node.ice;c.limited=false;c.storyNode=p.storyNode;c.variantId=p.storyNode===3?story.variant:null;c.patience=customers[id].patience*(s.day<=3?1.2:1)*(1+furnitureEffects(s).patience);}}if(!c.storyNode&&!c.tutorial&&p?.eventTriggered&&p.eventRemaining>0){let type=p.eventId==='school'?'student':p.eventId==='rain'?'relaxed':null;if(p.eventId==='friend'){const types=Object.keys(customers).filter(id=>!customers[id].story&&(customers[id].day||1)<=s.day&&(customers[id].store||1)<=s.storeLevel);type=types[Math.floor(g.random()*types.length)];}if(type){if(p.eventId==='friend')g.emit('townFriend',{customer:Object.keys(storyLines).find(id=>this.progress(id).met)||'adeng'});c.type=type;c.eventId=p.eventId;c.patience=customers[type].patience*(s.day<=3?1.2:1)*(1+furnitureEffects(s).patience);p.eventRemaining--;p.eventApplied++;this.experience(p.eventId);}}if(!c.storyNode&&storyLines[c.type]){const story=storyLines[c.type],v=variants[story.variant];if(s.collections.unlockedVariants.includes(story.variant)){c.recipe=v.recipe;c.variantId=story.variant;c.sugar=v.sugar;c.ice=v.ice;c.limited=false;}else if(!s.unlocked.includes(story.recipe)){c.type='student';c.recipe='pearlMilkTea';}}return c;}
 visit(c){const s=this.g.data,key='visit:'+c.id;if(s.rewardLedger[key])return;s.rewardLedger[key]=true;const p=this.progress(c.type),first=!p.met;p.met=true;p.visits++;p.lastVisitDay=s.day;if(!s.seenCustomers.includes(c.type))s.seenCustomers.push(c.type);if(first)this.discover('认识'+customers[c.type].name,'customer:'+c.type);this.achievements();}
 ready(){const g=this.g,c=g.current;if(!c)return;this.visit(c);if(c.storyNode&&!c.storyIntroSeen){c.storyIntroSeen=true;const p=this.progress(c.type);if(!p.heardNodes.includes(c.storyNode))p.heardNodes.push(c.storyNode);const n=storyLines[c.type].nodes[c.storyNode-1];this.dialogue(customers[c.type].name,[n.hello,...(p.failed?['这次也照订单上的口味来就好，慢慢做。']:[])],c.id+':intro');}g.persist();}
 dialogue(title,lines,id){this.g.data.storyDialogue={title,lines,id};this.g.persist();this.g.emit('storyDialogue',{dialogue:this.g.data.storyDialogue});}
 closeDialogue(){this.g.data.storyDialogue=null;this.g.persist();}
 discover(text,id){const s=this.g.data,p=s.dayPlan;if(p&&!p.discoveries.includes(text))p.discoveries.push(text);if(id){s.collections.readEntryIds=s.collections.readEntryIds.filter(k=>k!==id);}this.g.emit('collectionChanged');}
 grant(id,{cookies=0,furniture=null}={}){const g=this.g,s=g.data;if(s.rewardLedger[id])return false;s.rewardLedger[id]=true;if(furniture)s.ownedFurniture[furniture]=(s.ownedFurniture[furniture]||0)+1;if(cookies){g.costs.credit(cookies);if(g.day){g.day.income+=cookies;g.day.collectionReward=(g.day.collectionReward||0)+cookies;}}return true;}
 served(c,a){const g=this.g,s=g.data,plan=s.dayPlan;if(plan?.completedOrderIds.includes(c.id))return;plan?.completedOrderIds.push(c.id);const p=this.progress(c.type);if(a.rating>=4)p.goodServes++;
  const correct=a.rating>=4&&a.recipeCorrect&&a.sugarCorrect&&a.iceCorrect;
  if(correct&&c.drink.manualIce&&a.iceCorrect){s.craftStats.manualCorrect++;if(c.ice===1)s.craftStats.firstManual=true;}
  if(c.storyNode){if(correct&&c.storyNode===p.storyNode+1&&p.lastStoryDay<s.day){const story=storyLines[c.type],n=c.storyNode,key=`story:${c.type}:${n}`;if(this.grant(key,{furniture:n===3?story.furniture:null})){p.storyNode=n;p.lastStoryDay=s.day;p.failed=false;if(plan)plan.storyAdvanced=true;const lines=[story.nodes[n-1].reply];if(n===2){if(!s.collections.unlockedVariants.includes(story.variant))s.collections.unlockedVariants.push(story.variant);this.discover('学会'+variants[story.variant].name,'variant:'+story.variant);lines.push('已记进熟客配方本，下次依然会写清糖冰。');}if(n===3){this.discover('收到'+({granny:'手织杯垫',adeng:'暖光小灯',painter:'奶茶铺明信片'}[c.type]),'story:'+c.type);lines.push(c.type==='painter'?'已放进家具仓库，室内茶铺的墙面可以摆放。':'已放进家具仓库，可以放在柜台上。');}s.storyDialogue={title:customers[c.type].name,lines,id:c.id+':reply'};g.later(.85,()=>{if(s.storyDialogue)g.emit('storyDialogue',{dialogue:s.storyDialogue});});}}else{p.failed=true;this.discover('下次再试试'+customers[c.type].name+'的口味','story:'+c.type);}}
  this.achievements();
 }
 achievements(){const s=this.g.data,tests={handmadeFirst:s.craftStats.firstManual,handmade10:s.craftStats.manualCorrect>=10,friends6:Object.values(s.customerProgress).filter(p=>p.met).length>=6,oneStory:Object.values(s.customerProgress).some(p=>p.storyNode===3),threeVariants:s.collections.unlockedVariants.length===3,events3:s.collections.seenEventIds.length>=3};for(const a of achievementCatalog){if(tests[a.id]&&this.grant('achievement:'+a.id,{cookies:a.reward||0,furniture:a.furniture})){this.discover(a.name,'achievement:'+a.id);this.g.emit('collectionReward',{name:a.name,cookies:a.reward||0,furniture:a.furniture});}}}
 finishDay(){const s=this.g.data,p=s.dayPlan;if(!p||p.closed)return;p.closed=true;if(p.eventId==='postcard'&&!p.eventTriggered){p.eventTriggered=true;const i=p.postcardIndex??0;if(!s.collections.eventMessages.includes(i)){s.collections.eventMessages.push(i);this.discover('收到一张小镇来信','event:postcard');}this.experience('postcard');}if(p.eligible)s.storyMissDays=p.storyAdvanced?0:s.storyMissDays+1;this.achievements();}
 nextTarget(){const id=Object.keys(storyLines).find(id=>this.progress(id).storyNode===2);return id?{text:`再成功接待一次${customers[id].name}，收到小礼物`,type:'story',cost:0}:null;}
 experience(id){const s=this.g.data;if(!s.collections.seenEventIds.includes(id)){s.collections.seenEventIds.push(id);this.discover('经历'+events[id].name,'event:'+id);}this.achievements();}
 tick(){const g=this.g,p=g.data.dayPlan,a=g.day;if(!p||!a||a.status!=='open'||p.eventTriggered||!p.eventId||p.eventId==='postcard'||g.data.day<=3||g.paused||g.craft.teaching||g.craft.held||g.data.storyDialogue||g.growth.decorating||!['order','making','between'].includes(g.phase)||a.served<2||a.waiting.length>=storeLevels[g.data.storeLevel].capacity-1||a.spawned>=a.goal)return;p.eventTriggered=true;p.eventRemaining=events[p.eventId].count;if(p.eventId==='rain')this.experience('rain');g.emit('townEvent',{id:p.eventId,text:events[p.eventId].text});g.persist();}

}
export function normalizeTown(raw,s){const number=x=>Math.max(0,Math.floor(Number(x)||0));s.customerProgress={};for(const id of Object.keys(customers)){const old=raw.customerProgress?.[id];const p=freshProgress();if(old){p.met=old.met===true;p.visits=number(old.visits);p.goodServes=Math.min(p.visits,number(old.goodServes));p.storyNode=storyLines[id]?Math.min(3,number(old.storyNode)):0;p.lastStoryDay=number(old.lastStoryDay);p.lastVisitDay=number(old.lastVisitDay);p.heardNodes=Array.isArray(old.heardNodes)?[...new Set(old.heardNodes.filter(x=>[1,2,3].includes(x)))]:[];p.failed=old.failed===true;p.legacySeen=old.legacySeen===true;}else if(s.seenCustomers.includes(id)){p.met=true;p.legacySeen=true;}s.customerProgress[id]=p;}
 const c=raw.collections||{};s.collections={unlockedVariants:Array.isArray(c.unlockedVariants)?[...new Set(c.unlockedVariants.filter(k=>variants[k]))]:[],seenEventIds:Array.isArray(c.seenEventIds)?[...new Set(c.seenEventIds.filter(k=>events[k]))]:[],readEntryIds:Array.isArray(c.readEntryIds)?c.readEntryIds.filter(k=>typeof k==='string').slice(0,200):[],eventMessages:Array.isArray(c.eventMessages)?[...new Set(c.eventMessages.filter(k=>Number.isInteger(k)&&k>=0&&k<townMessages.length))]:[]};s.storyMissDays=number(raw.storyMissDays);
 const p=raw.dayPlan;s.dayPlan=p&&p.day===s.day?{day:s.day,storyCustomerId:storyLines[p.storyCustomerId]?p.storyCustomerId:null,storySerial:Math.max(1,Math.min(14,number(p.storySerial))),storyNode:Math.min(3,number(p.storyNode)),eligible:p.eligible===true,storyAdvanced:p.storyAdvanced===true,completedOrderIds:Array.isArray(p.completedOrderIds)?[...new Set(p.completedOrderIds.filter(x=>typeof x==='string'))].slice(0,14):[],eventId:events[p.eventId]?p.eventId:null,eventTriggered:p.eventTriggered===true,eventRemaining:Math.min(2,number(p.eventRemaining)),eventApplied:Math.min(2,number(p.eventApplied)),discoveries:Array.isArray(p.discoveries)?p.discoveries.filter(x=>typeof x==='string').slice(0,30):[],closed:p.closed===true,postcardIndex:Math.min(2,number(p.postcardIndex))}:null;
 if(raw.version<4&&raw.active){s.dayPlan={day:s.day,storyCustomerId:null,storySerial:3,storyNode:0,eligible:false,storyAdvanced:false,completedOrderIds:[],eventId:s.day>3&&raw.active.rushPlanned?'school':null,eventTriggered:raw.active.rushTriggered===true,eventRemaining:Math.min(2,number(raw.active.rushRemaining)),eventApplied:0,discoveries:[],closed:raw.active.status==='summary'};}
 const d=raw.storyDialogue;s.storyDialogue=d&&typeof d.title==='string'&&Array.isArray(d.lines)?{title:d.title.slice(0,40),lines:d.lines.filter(x=>typeof x==='string').slice(0,3).map(x=>x.slice(0,180)),id:String(d.id).slice(0,80)}:null;
 for(const id of s.milestones)s.rewardLedger['milestone:'+id]=true;
 for(const[id,p]of Object.entries(s.customerProgress)){for(let n=1;n<=p.storyNode;n++)s.rewardLedger[`story:${id}:${n}`]=true;}
}
