import {storyLines,variants,customerNotes,achievementCatalog,events,townMessages} from './town-data.mjs';
import {customers,drinkRecipes,recipeText,sugars,ices} from './data.mjs';
import {milestones,furnitureCatalog} from './growth-data.mjs';
import {miniCup} from './cup.mjs';
const $=id=>document.getElementById(id),escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export class TownUI{
 constructor(g,ui,audio,getScene){this.g=g;this.ui=ui;this.audio=audio;this.getScene=getScene;this.tab='customers';this.recipeTab='base';this.eventAge=0;this.rainAge=0;this.bind();}
 get s(){return this.g.data;}
 unread(id){return !this.s.collections.readEntryIds.includes(id);}
 read(id){if(!this.s.collections.readEntryIds.includes(id))this.s.collections.readEntryIds.push(id);this.g.persist();this.badge();}
 badge(){const s=this.s,unread=Object.entries(s.customerProgress).some(([id,p])=>p.met&&this.unread('customer:'+id))||s.collections.unlockedVariants.some(id=>this.unread('variant:'+id))||achievementCatalog.some(a=>s.rewardLedger['achievement:'+a.id]&&this.unread('achievement:'+a.id))||s.collections.seenEventIds.some(id=>this.unread('event:'+id));$('collection-open').textContent=unread?'图鉴 · 有新发现':'图鉴';}
 open(tab='customers'){$('more-menu').close();this.tab=tab;this.render();$('collection-page').showModal();this.audio.play('click');}
 render(){const s=this.s;for(const b of document.querySelectorAll('[data-collection-tab]'))b.classList.toggle('selected',b.dataset.collectionTab===this.tab);const root=$('customer-collection');root.className='town-cards '+this.tab;$('collection-note').textContent=this.tab==='customers'?'见过一面，再慢慢熟悉。':this.tab==='stories'?'已经发生的故事，随时回来看看。':'纪念每一步，不用再点一次领奖。';
  if(this.tab==='customers')root.innerHTML=Object.entries(customers).map(([id,c])=>{const p=this.g.town.progress(id);return `<button class="town-card ${p.met?'':'unknown'}" data-customer-entry="${id}"><span class="portrait"><img src="./assets/icon.png" alt=""><i>${p.met?c.icon:'？'}</i></span><b>${p.met?c.name:'还未相遇'}</b><small>${p.met?(this.unread('customer:'+id)?'新面孔 · ':'')+`到访 ${p.visits} · 好评 ${p.goodServes}`:storyLines[id]?'小镇里的一位客人':'下次会见到谁呢'}</small></button>`;}).join('');
  else if(this.tab==='stories'){root.innerHTML=Object.entries(storyLines).map(([id,l])=>{const p=this.g.town.progress(id);return `<button class="town-card story-card" data-story-entry="${id}"><span>${customers[id].icon}</span><b>${p.met?l.title:'待发现的小故事'}</b><small>${p.met?`${customers[id].name} · ${p.storyNode} / 3 段`:id==='granny'?'红豆茶香，会带来一位客人':id==='painter'?'等学会草莓奶茶，或许有人来画小店':'热茶也适合收工后的路上'}</small></button>`;}).join('')+s.collections.eventMessages.map(i=>`<button class="town-card story-card" data-letter="${i}"><span>✉</span><b>小镇来信 ${i+1}</b><small>一张收到的留言</small></button>`).join('')+s.collections.seenEventIds.map(id=>`<button class="town-card story-card" data-event-entry="${id}"><span>${id==='rain'?'☂':'✦'}</span><b>${events[id].name}</b><small>${this.unread('event:'+id)?'新经历 · ':''}留在营业里的片刻</small></button>`).join('');}
  else{root.innerHTML=achievementCatalog.map(a=>`<article class="town-card achievement ${s.rewardLedger['achievement:'+a.id]?'earned':''}"><span>${s.rewardLedger['achievement:'+a.id]?'✦':'○'}</span><b>${a.name}</b><small>${a.description}</small><em>${s.rewardLedger['achievement:'+a.id]?'已收藏':a.reward?`首次 +${a.reward} 🍪`:a.furniture?'纪念装饰':'纪念印章'}</em></article>`).join('')+milestones.map(m=>`<article class="town-card achievement ${s.milestones.includes(m.id)?'earned':''}"><span>◇</span><b>${m.name}</b><small>${m.kind==='cups'?'累计制作':'累计营业收入'} ${m.target}${m.kind==='cups'?' 杯':' 🍪'}</small><em>${s.milestones.includes(m.id)?'已领取 · 沿用经营记录':'继续在经营中达成'}</em></article>`).join('')+`<article class="town-card achievement"><b>店铺成长 LV${s.storeLevel}</b><small>沿用店铺升级进度，不另发第二份奖励</small></article>`;for(const a of achievementCatalog)if(s.rewardLedger['achievement:'+a.id])this.read('achievement:'+a.id);}
 }
 detail(title,html){$('detail-title').textContent=title;$('detail-content').innerHTML=html;$('collection-detail').showModal();}
 customer(id){const p=this.g.town.progress(id),c=customers[id];if(!p.met){this.detail('还未相遇','<p>开门迎客的时候，慢慢认识吧。</p>');return;}this.read('customer:'+id);const l=storyLines[id],notes=customerNotes[id];this.detail(c.name,`<img class="detail-avatar" src="./assets/icon.png" alt="${c.name}"><p>${escape(l?.impression||notes?.[0]||'来小店喝过茶的客人。')}</p><p>到访 ${p.visits} 次 · 四星以上 ${p.goodServes} 次</p>${p.legacySeen?'<small>旧版记得见过这位客人；分类次数从本版开始记。</small>':''}<h3>已知口味</h3><p>${p.goodServes>=3?escape(l?.preference||notes?.[1]):'还没聊到，再熟悉一些吧。'}</p>${p.goodServes>=5?`<h3>熟客留言</h3><p>${escape(l?.bio||'越来越熟悉这间小店，也记得奶蛙认真调茶的样子。')}</p>`:''}`);}
 story(id){const p=this.g.town.progress(id),l=storyLines[id];this.read('story:'+id);if(!p.met){this.detail('待发现的小故事','<p>先把小店经营起来，熟悉的茶香会带来相遇。</p>');return;}this.detail(l.title,`<p>${customers[id].name} · 已完成 ${p.storyNode} 段</p>`+l.nodes.map((n,i)=>i<p.storyNode?`<section class="story-node"><b>第 ${i+1} 次聊天</b><p>${escape(n.hello)}</p><p>${escape(n.reply)}</p></section>`:p.heardNodes.includes(i+1)?`<section class="story-node"><b>这次想点</b><p>${escape(n.hello)}</p><small>下次再照这个口味试试，不会错过。</small></section>`:'<section class="story-node muted">下一段，留给下一次相遇。</section>').join(''));}
 dialogue(d){$('story-speaker').textContent=d.title;$('story-accessory').textContent=Object.values(customers).find(c=>c.name===d.title)?.icon||'✦';$('story-lines').innerHTML=d.lines.map(x=>`<p>${escape(x)}</p>`).join('');if(!$('story-dialogue').open)$('story-dialogue').showModal();}
 recipes(tab=this.recipeTab){this.recipeTab=tab;for(const b of document.querySelectorAll('[data-recipe-tab]'))b.classList.toggle('selected',b.dataset.recipeTab===tab);if(tab==='base'){this.ui.recipeBookBase();return;}const s=this.s;$('recipe-cards').innerHTML=Object.entries(variants).map(([id,v])=>{const known=s.collections.unlockedVariants.includes(id);return `<article>${known?`${miniCup(drinkRecipes[v.recipe])}<b>${v.name}</b><small>${drinkRecipes[v.recipe].name} · ${drinkRecipes[v.recipe].price} 🍪</small><p>${recipeText(v.recipe)}</p><p>${sugars[v.sugar]} · ${ices[v.ice]}</p><small>来自${customers[v.customer].name}</small>`:`<div class="locked-cup">？</div><b>待发现的熟客配方</b><p>${v.customer==='granny'?'一杯适合慢慢喝的红豆':v.customer==='adeng'?'忙碌过后，也想歇一会儿':'把粉色好心情画下来'}</p>`}</article>`;}).join('');for(const id of s.collections.unlockedVariants)this.read('variant:'+id);if(!$('recipe-book').open)$('recipe-book').showModal();}
 summary(){this.weather();const p=this.s.dayPlan;const discoveries=p?.discoveries.slice(0,2)||[];$('daily-discoveries').innerHTML=discoveries.length?'<small>今日新发现</small>'+discoveries.map(x=>`<p>✦ ${escape(x)}</p>`).join(''):'';}
 souvenir(item){const id=item.id,lines={grannyCoaster:'“这是我织的小杯垫，放在店里吧。” — 奶蛙奶奶',townPostcard:'“不是大店才值得被画下来，你这家也很好看。” — 画画的小客人',handDrawnMenu:'午后红豆、收工小憩、莓好心情。每一杯都有认识的人。'};if(!lines[id])return;this.detail(furnitureCatalog[id].name,`<img class="souvenir-preview" src="${this.getScene().shopArt.thumbnail('furniture',id)}" alt="${furnitureCatalog[id].name}"><p>${lines[id]}</p>`);}
 event(e){$('event-banner').textContent=e.text;$('event-banner').hidden=false;this.eventAge=3;this.weather();this.audio.play(e.id==='rain'?'rain':'happy');}
 weather(){const p=this.s.dayPlan,rain=p?.eventId==='rain'&&p.eventTriggered&&this.g.day?.status==='open'&&!this.s.settings.lowEffects;$('weather-layer').hidden=!rain;if(rain&&!$('weather-layer').childElementCount)$('weather-layer').innerHTML=Array.from({length:14},(_,i)=>`<i style="left:${i<7?i*3:80+(i-7)*3}%;animation-delay:${(i%5)*-.21}s"></i>`).join('');}
 tick(dt){if(this.eventAge>0){this.eventAge-=dt;if(this.eventAge<=0)$('event-banner').hidden=true;}if(!$('weather-layer').hidden){this.rainAge+=dt;if(this.rainAge>5){this.rainAge=0;this.audio.play('rain');}}}
 bind(){$('collection-open').onclick=()=>this.open();$('next-target').onclick=()=>{const t=this.g.growth.nextTarget();if(t.type==='story')this.open('stories');else if(t.type==='store')document.getElementById('store-open').click();else if(t.type==='equipment')document.getElementById('equipment-open').click();else document.getElementById('decor-open').click();};
 this.ui.recipeBookBase=this.ui.recipeBook.bind(this.ui);this.ui.recipeBook=()=>this.recipes('base');
 const done=()=>{this.g.town.closeDialogue();$('story-dialogue').close();};$('story-close').onclick=done;$('story-back').onclick=done;$('story-dialogue').addEventListener('cancel',e=>{e.preventDefault();done();});
 document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;const d=b.dataset;if(d.collectionTab){this.tab=d.collectionTab;this.render();}if(d.customerEntry)this.customer(d.customerEntry);if(d.storyEntry)this.story(d.storyEntry);if(d.recipeTab)this.recipes(d.recipeTab);if(d.letter!==undefined)this.detail('小镇来信',`<p>${townMessages[Number(d.letter)]}</p>`);if(d.eventEntry){this.read('event:'+d.eventEntry);this.detail(events[d.eventEntry].name,`<p>${events[d.eventEntry].text}</p>`);}});this.badge();}
}
